### ISSUE TITLE
Language selection for "games"

### ISSUE THREAD

**Issue by just-alex** [twireapp/Twire#120]
"Top streams and games now only show streams in your system language."
Please include an option to turn this off.
Or even better let me select which languages should be displayed.
I would like to browse through games, without the need for the search as I don't know yet what I want to watch..

Oh and maybe also include a link to this github and/or a changelog into the app. It took me quite a while to realise that this was a "feature" of the app and not twitch being shitty.

Great work btw :) especially it being FOSS. Thank You!

**Comment by samfundev** [comment]
There is actually going to be an option to disable this change: #115. It's not out in the current version of Twire but it'll be out in the next update. Would that be good or would you want to select the languages?

If I may ask, I'm a bit confused what you mean by "I would like to browse through games without...search". I'm confused because this change doesn't effect Top games, just when you click into a specific game and look at streams of that game. Looking back at how I worded the change, it may have been confusing.

Adding a changelog sounds like a great idea. I could show a changelog when you open the new version of the app.

Thanks for the kind words, really appreciate it.

**Comment by just-alex** [comment]
For me either is fine, I just want to be able to easily scroll through the 
the English streams of the game I choose while keeping my phone in my local 
language.
That might be different though for someone who prefferes multiple not so 
popular languages, i such a person even exists...

My "stream-finding-workflow" right now is as follows:
Decide which game I want to watch
Search for the name of the game
Scroll through kinda unsorted results as many people have that in their name...
Hopefully find something.
Of course there is only a problem when you want to watch one of the mayor 
games, but would be nice if there was none at all ;)

TL/DR: Selection would be the optimal way for everybody (preferably easily 
accessible, maybe via a flag icon in the respective screen), an option to 
turn off any filter is enough for me :)

Thank you for taking your time and listening to your users. This is very 
much apprichiated :)
Maybe FOSS apps need some kind of user opinion question air inapp because 
they lack the 5trillion trackers of "normal" apps.
I'm still sad about the big  changes in Transportr some while ago. Before 
it was the (for me) very best public transport connection finder still had 
much to improve on (what year will the planner arrive whom I can tell that 
I'm OK with walking, even longer distances, as long as its faster, or that 
let's me define areas or lists as destination (eg. home is the train 
station or the bus stop near my house, downtown is any stop in that 
area....) or... - I'm getting too much offtopic here), now it is just a 
(for me) meh FOSS alternative. But maybe I am not the majority user, who 
knows? Nobody..  So I guess the best way for these kind of things is to ask 
the users directly - in app and easy to reply to, not wait for (positive or 
negative) feedback.

Shame on me, the offtopic is more than what I contribute... I'm out ;)

Am 24. August 2020 17:32:38 schrieb Sam <notifications@github.com>:
