### ISSUE TITLE
Can't chat : send button is red

### ISSUE THREAD

**Issue by KaKi87** [twireapp/Twire#186]
Although, when clicking it, the input is cleared.

---

Thanks

**Comment by KaKi87** [comment]
Hello @samfundev, we do not get notifications nor emails when you change tags, please send messages to notify us.

I thought you would know what I meant because it's a very specific effect that I thought would have been created on purpose.

Here is the initial state of the input :

![](https://i.goopics.net/NgmvR.jpeg)

Then, here is its state when writing something :

![](https://i.goopics.net/9Gdqy.jpeg)

Clicking on the button will clear the input but not send the message.

Thanks

**Comment by samfundev** [comment]
@KaKi87 Oh, I didn't know that. In this case, this is an issue that I needed to explore further so you didn't need to do anything further.
Just to clarify something, the send button turns red because it's indicating that you can send a message since you have a message typed in. It's using the accent color of the theme you have selected. I can understand how this can be confusing though.

**Comment by JohnVeness** [comment]
Maybe same as #128?

**Comment by samfundev** [comment]
Closing due to a lack of information.
