### ISSUE TITLE
VODs fail to play (because of mature audience flag?)

### ISSUE THREAD

**Issue by aladar42** [twireapp/Twire#215]
Currently, clicking on VODs flagged as for mature audiences causea the stream to fail instantly with a "stream couldnt be played" error message.

**Comment by Nickwasused** [comment]
Do you have some example links for mature Vods that don't play?

**Comment by aladar42** [comment]
Yeah, almost everything from this channel, for instance:

https://www.twitch.tv/hannahreloaded

-------- Original Message --------

**Comment by Nickwasused** [comment]
So, I tried to play the last 12 Vods from the Channel you mentioned and all of them loaded and played fine. (See Vods in the Picture.)
![](https://i.imgur.com/hRS3Vc7_d.webp)
For testing, I used the lasted Version from Github which is: https://github.com/twireapp/Twire/commit/76d849c6a476c91e7f1c3843a5e606b78a899ee8

Maybee this Info could help to identify the problem:
1. The Version of the App (e.g. 2.9.3, 2.9.2, or other Builds)
2. The Country you live in (Maybee this is just a problem with a specific country)
3. Are you logged in (Account or No Account)
4. What is your Android Version (e.g 11, 10, 9)

**Comment by aladar42** [comment]
>The Version of the App (e.g. 2.9.3, 2.9.2, or other Builds)

The latest on F-Droid. I believe 2.9.2?

>The Country you live in (Maybee this is just a problem with a specific country)

Czech Republic

>Are you logged in (Account or No Account)

Not logged in

>What is your Android Version (e.g 11, 10, 9)

8.0.0

-------- Original Message --------

**Comment by Nickwasused** [comment]
So I recreated an Installation with the setup you stated. I used the lasted version from F-Droid (https://f-droid.org/repo/com.perflyst.twire_523_src.tar.gz), with an Android Virtual Device using Android 8.0 and Protonvpn to get Servers from the Czech Republic. (See Picture)
![](https://i.imgur.com/AoDnNGS.png)

I have encountered no problems with playing Vods.

Possible Problems on your end:

- Your Internet Service Provider has a problem with routing stuff to the Twitch servers.
- Your Home Network Setup has a Problem (e.g. Pihole blocking something or firewall rules.)

Test you can perform:

1. Try to watch the Vod in a Browser on another Device
2. Try to use a VPN or Data Plan on your Android Device to see if the Problem is related to your Network.

**Comment by fefo-dev** [comment]
Had this issue consistenty on every channel with Twire 2.9.3 - VODs simply don't work. No issues otherwise on browsers, main Twitch app or other devices.

The artifact from https://github.com/twireapp/Twire/pull/240 fixed the issue ([direct link](https://github.com/twireapp/Twire/suites/3484603216/artifacts/82912330), login required). No commit suggests a fix so dunno where the issue stems from.

**Comment by aladar42** [comment]
I'm on 2.9.3 and all VODs work fine now, even though you said you have the issue on that version. Weird.

-------- Original Message --------
