### ISSUE TITLE
Bump minSdk to 21 / Drop support for KitKat and below

### ISSUE THREAD

**Issue by TacoTheDank** [twireapp/Twire#362]
These outdated versions are insecure, and the 3.x line of OkHttp is no longer maintained. See [this](https://github.com/TeamNewPipe/NewPipe/pull/7613).

If this is too large of a jump, it can be done first with a minSdk bump to 19.

I'm willing to work on this if you agree with the proposition.

**Comment by samfundev** [comment]
OkHttp dropping support for KitKat is a pretty big deal. Plus, I don't think I am able to keep up with fixing up bugs on old versions. I think it's probably best to move on and drop support for KitKat. I appreciate any help that you would be able to provide, especially since there was many things that were cleaned up in NewPipe that I would have missed.

**Comment by TacoTheDank** [comment]
Sure thing 👍
