### ISSUE TITLE
[Feature Request] Add support for low latency

### ISSUE THREAD

**Issue by ghost** [twireapp/Twire#94]
I don't know if this is possible, but it would be great because right now stream is delayed around 15 seconds.

**Comment by anon88391** [comment]
Is this going to be implented?
Personally I can't use Twire because of the high latency, because people in the chat react to everything 5 seconds before I even see what they're reacting to.
I saw @samfundev say that the issue is proprietary software in #199, but many open source players like mpv can easily play streams in low latency mode when used with streamlink.
